name: HeartStory
main: com.heartstory.HeartStoryPlugin
version: 1.0
api-version: 1.20
description: Heart Story Engine bridge

commands:
  loadlevel:
    description: Load story level
    usage: /loadlevel <level>
  sayai:
    description: Send text to AI
    usage: /sayai <text>
