id: gm4_balloon_animals
name: Balloon Animals
version: 1.3.X

data_pack:
  load: .

output: build

pipeline:
  - local_manifest_stub.ensure_manifest
  - gm4_balloon_animals.generate
  - gm4.plugins.module.default_pack_icon
  - gm4.plugins.module.gm4_root_advancement
  - gm4.plugins.versioning.modules
  - gm4.plugins.upgrade_paths
  - gm4.plugins.include.lib_trades
  - mods.gm4_balloon_animals_plugins
  - mecha
  - fix_pack_format

require:
  - bolt

meta:
  gm4:
    versioning:
      required:
        lib_trades: 1.6.0
      schedule_loops: [main]
    website:
      description: Looking for exotic animals? This module makes some Wandering Traders sell cute baby animals!
    modrinth:
      project_id: zKRZZHQ3
    wiki: https://wiki.gm4.co/wiki/Balloon_Animals
    credits:
      Creator:
        - TheEpyonProject
      Icon Design:
        - Hozz
    model_data:
      - item: lead
        reference: gui/advancement/balloon_animals
        template:
          name: advancement
          forward: minecraft:item/lead
